cat > nixpacks.toml << 'EOF'
[phases.setup]
nixPkgs = ['nodejs', 'php81', 'php81Packages.composer']

[phases.build]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'chmod -R 755 storage bootstrap/cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT'
EOF